# noise-airq weights configuration
# Scope: minute-level fusion of ambient TEMPERATURE (TEMP) and HUMIDITY (HUM)
# Assumes: you already apply your per-sensor calibration (offset/gain/non-linear) BEFORE weighting.
# Basis: datasheet accuracy near room conditions + response dynamics at 1-minute cadence.

weights:
  TEMP:
    ENVIRO: 1.00  # BME280-class on Enviro: ±0.5 °C (0–65 °C), fast τ63%≈1 s, board-exposed → best ambient reference.
    DHT22:  0.85  # DHT22: <±0.5 °C, repeat ±0.2 °C; slower sampling (~2 s) and higher practical variance/drift than BME280.
    SCD30:  0.70  # SCD30 module: ±0.4 °C @25 °C but inside NDIR cell; slower (τ>10 s) + self-heating → de-weight for ambient.

  HUM:
    ENVIRO: 1.00  # BME280-class: ±3 %RH, hysteresis ±1 %RH, τ≈1 s → fast/stable ambient response at 1-min bins.
    DHT22:  0.85  # DHT22: ±2 %RH spec (max ±5), repeat ±1 %RH; good but tends to drift/age → strong secondary.
    SCD30:  0.80  # SCD30: ±3 %RH, excellent repeatability (±0.1 %RH) but τ≈8 s inside module → slower dynamics.

# --- Optional: machine-readable rationales (kept separate from weights; comments aren’t parsed) ---
rationales:
  TEMP:
    ENVIRO: "Primary ambient reference: fast (τ≈1 s), ±0.5 °C; best placement."
    DHT22:  "Similar accuracy, slower sampling and more drift; good secondary."
    SCD30:  "Accurate @25 °C but slow/self-heated inside NDIR; tertiary for ambient."
  HUM:
    ENVIRO: "Fast response (τ≈1 s), ±3 %RH; stable ambient measurement."
    DHT22:  "Best nominal accuracy (±2 %RH) but higher drift; secondary."
    SCD30:  "±3 %RH with great repeatability but τ≈8 s; slower dynamics."

# Metadata (helps reproducibility)
meta:
  version: 1
  last_updated: 2025-08-16
  operating_range: "20–30 °C, 30–70 %RH"
  notes: >
    Weights reflect datasheet accuracy near room conditions and response time at 1-minute aggregation,
    after your own calibration. If Enviro is missing for a kit/time, just use the available sensors—weights
    are normalized by the sum automatically.
